- hosts: all

  tasks:
    - name: Find all files older than {{ 3d }} in {{ /home/ec2-user/ansible-practice/  }}
      find:
         paths: "{{ path }}"
         age: "3d"
         recursive: yes
      register: ansiblelog

    - name: Delete files older {{ 3 days }}
      file:
         path: "/home/ec2-user/ansible-practice/"
         state: absent
      with_items: ansiblelog



  
  